site_name: Ashscripts
site_url: https://ashscripts.github.io/
repo_url: https://github.com/Ashscripts/Ashscripts.github.io

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - PowerShell:
      - Generic Scripts: powershell/generic-scripts/index.md
  - PSADT:
      - 4.17: psadt/4.17/index.md