site_name: Ashscripts
site_url: https://ashscripts.github.io/
repo_url: https://github.com/Ashscripts/Ashscripts.github.io

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav:
  - Home: index.md
  - PowerShell:
      - Generic Scripts:
          - Overview: powershell/generic-scripts/index.md
          - Fetch Installed Applications: powershell/generic-scripts/fetch-installed-applications.md
  - PSADT:
      - 4.17: psadt/4.17/index.md